services:
  downtify:
    container_name: downtify
    image: 'downtify:${TAG-latest}'
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./downloads/docker:/downloads
    environment:
      - CLIENT_ID=5f573c9620494bae87890c0f08a60293  # Optional
      - CLIENT_SECRET=212476d9b0f3472eaa762d90b19b0ba8  # Optional