[project]
name = "downtify"
version = "0.3.2"
description = "Self-hosted Spotify downloader"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.2.0",
    "fastapi>=0.103.2",
    "jinja2>=3.1.5",
    "load-dotenv>=0.1.0",
    "python-multipart>=0.0.20",
    "requests>=2.32.3",
    "spotdl>=4.2.11",
]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
    "taskipy>=1.14.1",
    "httpx==0.27.2",
]
doc = [
    "mkdocs>=1.6.1",
    "mkdocs-material[imaging]>=9.6.7",
]

[tool.uv]
upgrade = true

[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.ruff.lint.per-file-ignores]
"main.py" = ["E501"]

[tool.pytest.ini_options]
pythonpath = '.'
addopts = '-p no:warnings'

[tool.taskipy.tasks]
lint = 'ruff check .; ruff check . --diff'
format = 'ruff format .; ruff check . --fix'
run = 'uvicorn main:app --host 0.0.0.0 --reload'
export = 'uv export --no-hashes --no-dev -o requirements-app.txt'
doc = 'mkdocs serve'
export-doc = 'uv export --no-hashes --only-group doc -o requirements.txt'
